- src/operator/search.ts
- src/types.ts
- src/view/htmlElement.tsx
> fix(search): searching in HTML content

- .travis.yml
See https://travis-ci.org/github/grid-js/gridjs
> CI is not running on Travis

- src/storage/storageUtils.ts
> fix(from): cast the cells to HTML if it is not text

- .github/workflows/nodejs.yml
- package.json
> chore: updating node version

- src/grid.ts
> fix(forceRender): checking this.config first

- .all-contributorsrc
- README.md
> Revert "docs: add MelvinIdema as a contributor"

- src/operator/search.ts
> fix(search): checking props of element object

- src/pipeline/pipeline.ts
- tests/pipeline/pipeline.test.ts
> fix(pipeline): unregister should check the steps datatype (#125)

- src/pipeline/transformer/storageResponseToArray.ts
- src/types.ts
- tests/pipeline/transformer/storageResponseToArray.test.ts
> feat: id should accept a function as well

- src/pipeline/initiator/server.ts
- src/storage/server.ts
- tests/storage/server.test.ts
> Adding `data` callback to ServerStorage

- package-lock.json
- package.json
- src/pipeline/initiator/server.ts
> fix(server): Server initiator must remove functions from args

- packages/gridjs/src/storage/storageUtils.ts
- packages/gridjs/src/util/html.ts
> Decode HTML escape sequences when importing from a HTML table

- packages/gridjs/src/config.ts
- packages/gridjs/src/view/table/tr.tsx
- packages/gridjs/tests/view/table/tr.test.tsx
> feat: adding tr className to the config object

- packages/gridjs/src/i18n/it_IT.ts
> Created it_IT.ts

- packages/gridjs/index.ts
- packages/gridjs/src/i18n/fr_FR.ts
- packages/gridjs/src/i18n/language.ts
I translated the en_US language file to add support for french.
I like this module and I think that it would be nice to have other languages setup by default in it.
> Added support for French

- packages/gridjs-selection/package-lock.json
- packages/gridjs-selection/package.json
- packages/gridjs/package-lock.json
- packages/gridjs/package.json
> Revert "chore(deps-dev): bump @typescript-eslint/parser from 2.34.0 to 4.22.0"

- packages/gridjs-selection/package-lock.json
- packages/gridjs-selection/package.json
- packages/gridjs/package-lock.json
- packages/gridjs/package.json
> Revert "chore(deps-dev): bump eslint from 6.8.0 to 7.24.0"

- i18n/index.ts
- i18n/tr_TR.ts
i added my native language support as a first contribution
> add turkish language support

- package-lock.json
- package.json
- plugins/selection/package-lock.json
> chore: changing postinstall to prepare

- l10n/index.ts
- l10n/ru_RU.ts
Hello! Great project! Here is my little contribution to it :)
> Add new locale (ru_RU)

- l10n/index.ts
- l10n/ja_JP.ts
created ja_JP loacale file :)
Japanese word order is different from western languages' one, so partially it is not a literal translation.
> Add Japanese locale (ja_JP)

- l10n/index.ts
- src/i18n/ms_MY.ts
Added translations in Malay language
> Add Malay translation

- plugins/selection/src/rowSelection/rowSelection.tsx
- src/state/store.ts
- tests/jest/state/store.test.ts
Updates the Selection plugin and simplifies the way props are defined. Also adding some Store tests.
> fix(plugins/selection): remove the props.id and other unused props

- l10n/sv_SE.ts
Added Swedish translation for Grid.js.
> Added Swedish translation (sv_SE)

- src/i18n/th_TH.ts
Hello Maintainer. This PR has been added Thai language for i18n hope you approve it. Thank you.
> add: i18n th_TH
